services:

  postgres:
    image: postgres:16
    container_name: voiture_shop_db
    environment:
      POSTGRES_DB: voituredb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d voituredb"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: voiture_shop_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build: ./SpringDataRest
    container_name: voiture_shop_backend
    ports:
      - "8089:8089"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-829984716736-a9sbqv7r9mcjajlbvolfq5fm2drc5pn8.apps.googleusercontent.com}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-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}
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started

  frontend:
    build: ./myapp
    container_name: voiture_shop_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  ollama_data:
